[package]
name = "match_template"
version = "0.0.1"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full", "extra-traits", "fold"] }
quote = "1"
proc-macro2 = "1"
