[package]
name = "test_util"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
rand = "0.6.5"
rand_isaac = "0.1.1"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
time = "0.1"
