[package]
name = "tikv_util"
version = "0.1.0"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
slog-term = "2.4"
byteorder = "1.2"
rand = "0.7"
quick-error = "1.2.2"
tempfile = "3.0"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.8"
protobuf = "2"
utime = "0.2"
chrono = "0.4"
lazy_static = "1.3"
backtrace = "0.3.9"
url = "2"
regex = "1.0"
futures = "0.1"
futures-cpupool = "0.1"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
tokio-core = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"
tokio-threadpool = "0.1.13"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
grpcio = { version = "0.5.0-alpha.3", features = [ "secure" ] }
crossbeam = "0.7.2"
fail = "0.3"
fxhash = "0.2.1"
zeroize = { version = "0.10", features = [ "alloc" ] }

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "7dd3d42f0c21384950afe6a46ed85352acf71625"
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "7dd3d42f0c21384950afe6a46ed85352acf71625"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs" }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
raft = "0.6.0-alpha"

[[bench]]
name = "channel"
path = "benches/channel/mod.rs"
