[package]
name = "tidb_query_datatype"
version = "0.0.1"
edition = "2018"
publish = false
description = "TiKV query engine data types"

[dependencies]
bitflags = "1.0"
failure = "0.1"
num-traits = "0.2"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
