[package]
name = "keys"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
byteorder = "1.2"
derive_more = "0.15.0"
failure = "0.1"
hex = "0.3"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
slog = "2.3"

tikv_alloc = { path = "../tikv_alloc", default-features = false }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }