[package]
name = "tidb_query_codegen"
version = "0.0.1"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
darling = "0.10"
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
heck = "0.3"
